### ISSUE TITLE
deploy the site automagically

### ISSUE THREAD

**Issue by samjewell** [jlord/git-it#136]
we should add some kind of Continuous Deployment (travis / circleCI) so that when the guide gets updated it is deployed both to http://jlord.us/git-it/ and to the served up version inside the NPM package

**Comment by cronopio** [comment]
Running the command: `npm run deploy` will commit and push to the `gh-pages` and this make it the guide available over the web. To make it available over NPM, it will an additional step: `npm publish`

If you have correct privileges this commands should deploy without issues. In my personal opinion we don't need automagically continuous deployment since run `npm run deploy && npm publish` its very simple and quick.

**Comment by samjewell** [comment]
Fair enough. At the start my work got merged, but hadn't been deployed, but it's all live now, and your comment makes sense :-)
