### ISSUE TITLE
running git-it server should open a browser window

### ISSUE THREAD

**Issue by samjewell** [jlord/git-it#137]
Running `git-it server` should automatically open a new browser window/tab and show you the page, so you don't have to manually enter the localhost URL. Some people have never done this before, and everything is so much easier with a browser that starts automatically.

At a later date we could even make the whole thing a "Single page application" - that way it wouldn't even matter if the server got killed (we could kill it ourselves even) - the browser would still have the page (whole site) in memory!

**Comment by jlord** [comment]
I actually started out by having it open a browser window, but this doesn't work the same across platforms so I decided to opt out of it entirely figuring it wouldn't be that hard to copy the link. 

Most of the time now I just recommend the web version of the guide since they have to be online anyways to use Git-it. The one that ships with Git-it can then just be there if they need it offline sometime. 

Not clear what you're thinking re: single page app. I've thought about how it would be cool to have the app and website respond to each other or be in the same thing, but it would be pretty complicated since we need to access Git and such.

**Comment by samjewell** [comment]
Good point that users need to be online anyway, so they may as well use the hosted version of the guide.

So could we do as suggested in https://github.com/jlord/git-it/issues/82 - point them **First** at the hosted version, and **second** at the local copy?

ie.
first recommend they go to
`http://jlord.us/git-it/`

And the fallback to:
`/usr/local/lib/node_modules/git-it/guide/index.html`

Instead of first recommending
`To launch the guide, run: `git-it server`

And falling back to:
`/usr/local/lib/node_modules/git-it/guide/index.html`

as it currently does:
![screen shot 2015-01-14 at 18 59 12](https://cloud.githubusercontent.com/assets/2903904/5745367/1d825658-9c20-11e4-954a-3a6ebe4499a1.png)

Lastly, if we do this, can we remove the server from the repo entirely? To simplify it and make it easier to understand and work with?

Thanks!

**Comment by samjewell** [comment]
Oh, and regarding the single page app - I just meant that we could have all 9 sets of instructions in one server request, and use javascript to show different 'pages'.
Would mean you could start the server, boot chrome and show the page, and immediately kill the server again - all 9 pages would be loaded into Chrome by then.
But would prefer to remove the server entirely if at all possible...!

**Comment by cronopio** [comment]
Maybe an option could be `opener` https://www.npmjs.com/package/opener if you want to get into this discussion again

**Comment by jlord** [comment]
I don't know how I missed the rest of the Jan. comments here—sorry!

At some point since then I've updated what it says at the bottom of each challenge to first suggest the web view and then to print out the location of the static files in the user's system. They can paste that in their browser if they are offline. This resolves needing to worry about a server.

Also! I'm in the process of [porting Git-it](http://github.com/jlord/git-it-electron) over to [Electron](http://electron.atom.io), which will make it a desktop app so basically the guide will become an app and this will definitely no longer be an issue :sparkles: 

If you update your version of Git-it you should should see the latest footer about the Guide. I think we can close this here.
