### ISSUE TITLE
git config --global user.username

### ISSUE THREAD

**Issue by nathan-j-brenner** [jlord/git-it#167]
I'm failing the githubbin section, which is weird because I've been using gitHub for a few months sending commits, pushing, pulling, ect. When I type git config user.name, I get my gitHub username.  On a side note, lately when I've been pushing up to gitHub, I've been requested for my gitHub username and password whereas there was a time I didn't have to do that every time. Any suggestions?

**Comment by jlord** [comment]
Hey!

Usually when you set up Git you add your _email_ and _name_ to your Git config. So that Git-it can know who you are on GitHub (to verify challenges) it asks you to also add another field, _username_. 

From your message above you're mentioning `user.name` which should be your full name (or whatever you want to represent your full name:) (for me 'Jessica Lord'). But for Git-it you should also be adding `user.username` and setting it to your GitHub username (case sensitive) (for me 'jlord').

```bash
$ git config --global user.username "nathan-j-brenner"
```

Seems like that's may be all that's going on—give it a try and let me know if it works out!

**Comment by nathan-j-brenner** [comment]
Thanks for the quick feedback, and I saw your feedback on the other post. When I type git confit --global user.username and .user and .email, I get the expected results

**Comment by jlord** [comment]
Closing because #170 should have fixed this.
