### ISSUE TITLE
Translating exercises 

### ISSUE THREAD

**Issue by leftieFriele** [jlord/git-it#178]
How would you go about translating the exercises in the git-it workshop? Is it just a matter of add a problem-<locale>.txt?

**Comment by jlord** [comment]
Hiya!

We have one non-English language Guide available, Traditional Chinese, and the way we did that was to duplicate the `raw-content` folder for each challenge and name it `raw-content-zhtw`. In that each line was translated by hand, then we worked it into the static pages generation. Not exactly the fanciest flow, but that's how we did it.

We haven't translated the text that appears on the terminal before, but yes, it would have to with editing the `problem.txt` of each challenge as well as the challenge names and footer text that appears in other screens (I believe those happen in my fork of `workshopper`). Then a way to switch between terminal languages would have to be built. I would suggest not doing this because I am re-writing the app to no use terminal so it would likely be obsolete before it was translated :grin: 

The new version is [jlord/git-it-electron](http://github.com/jlord/git-it-electron) which makes it so the Guide is the only text/interface for Git-it. So, if you translate the Guide as described in the first paragraph we could work that into the new version :sparkles: 

Hope that makes sense, let me know if you have any other questions!
