### ISSUE TITLE
i18n support?

### ISSUE THREAD

**Issue by marocchino** [jlord/git-it#180]
I looked your code little bit. and I found you use custom workshopper. so, It's not simple to make PR.
Do you have plan for support i18n or update workshopper?
thanks.

**Comment by jlord** [comment]
I don't currently have plans to build that support myself, though pull requests are welcome! I'm currently working on moving Git-it to use Electron, which means it will no longer use workshopper at all (it will be a desktop app that users download rather than installing with npm after installing Node). It will, however, still be matching Git responses based on English output. 

I'll close this issue here, but checkout the Git-it Electron repo: [jlord/git-it-electron](http://github.com/jlord/git-it-electron), and if you have ideas on supporting i18n there, let me know!
