### ISSUE TITLE
Branches Aren't Just For Birds problem

### ISSUE THREAD

**Issue by CodeStrider35** [jlord/git-it#181]
when i "git push origin add-CodeStrider35" and i verify my login and password, it says: remote: permission to jlord/patchwork.git denied to CodeStrider35. Fatal: unable to access 'https://github.com/jlord/patchwork.git/': The requested URL returned error: 403

my file "add-CodeStrider35.txt" is saved in the contributors folder.

I tried to go back and follow the steps again on http://jlord.us/git-it/challenges/branches_arent_just_for_birds.html and now its saying my branch's directory is clean...nothing to add or commit but my file is in the contributors folder...I'm so lost.

**Comment by jlord** [comment]
> Fatal: unable to access 'https://github.com/jlord/patchwork.git/': The requested URL returned error: 403

This would come from you trying to push to _my_ repository rather than _your fork_ of it. Check your remotes:

```
$ git remotes -v
```

You should have one that points to _your fork_, which should be: `https://github.com/CodeStrider35/patchwork.git`. In Git-it, the remote named `origin` should point to your branch while the one named `upstream` should point to mine, and is just for pulling (not pushing, since you don't have access to change the code in another person's repository unless you're added as a collaborator).

You can rename `origin` to `upstream` by running:

```
$ git remote rename origin upstream
```

Then you can add a remote to point to your fork:

```
$ git remote add origin https://github.com/CodeStrider35/patchwork.git
```

You'll be able to push to `origin` now :+1:  Hope that helps!

**Comment by CodeStrider35** [comment]
I'll try this when I get in - just wanted to say thank you on your answer. I appreciate how  you laid out the issue and provided the solution!

**Comment by CodeStrider35** [comment]
@jlord - still having problems - I make the file in patchwork/contributors as add-CodeStrider35. the file has my name as specified 'CodeStrider35'. The check in process is what is not working for me. next I put git status and it says 'On branch add-CodeStrider35, nothing to commit, working directory clean. Then I put git add add-CodeStrider35.txt and it says 'fatal: pathspec 'add-CodeStrider35.txt did not match any files. Then I put git add contributors/add-CodeStrider35.txt. nothing happens, it just goes to the next C:\patchwork>
Thinking that I finished that step, I go to the next and type: git commit -m "my first branch" and it says, On branch CodeStrider35, nothing to commit, working directory clean. I believe something went wrong here but as I'm typing directions verbatim, I go to the next and type git push origin CodeStrider35 and it gives me the same error message I typed in my first.

**Comment by CodeStrider35** [comment]
I tried your directions to and it just says fatal: remote origin already exists...

**Comment by CodeStrider35** [comment]
@jlord - problem fixed!!! TY

**Comment by jlord** [comment]
Oh, good! How did you fix it? It may help others down the line who have the same issue.

**Comment by CodeStrider35** [comment]
programmer friend helped me - I'll ask for the steps again and I'll post here asap.

**Comment by kevintrogers** [comment]
I ran into this same problem. Your answer was great in that it helped me to understand what the issue was so thanks for that, but this http://stackoverflow.com/questions/3011402/leaving-github-how-to-change-the-origin-of-a-git-repo helped me to figure out how to fix it. I found the second answer to be very simple to implement.

**Comment by YashGulati** [comment]
this helped me too.
