### ISSUE TITLE
GITHUBBIN issue

### ISSUE THREAD

**Issue by LiamVM** [jlord/git-it#214]
Hello, I couldn`t pass this challenge, until I changed line:
$ git config --global *user.username* ...
to:
$ git config --global *user.name* ...

Please, take this bug into consideration

**Comment by jlord** [comment]
I'm not sure why it worked that way for you. You specifically need to use `user.username` because `user.name` is for something else. You'll need to have `user.username` set for other challenges as well.

You can see here where it checks for `user.username` [here](https://github.com/jlord/git-it/blob/master/problems/githubbin/verify.js#L11). You can type the same thing into your terminal to see what you have set and see what Git-it is using as your GitHub username:

```
git config user.username
```
