### ISSUE TITLE
Branches arent just for birds - cannot push

### ISSUE THREAD

**Issue by joannesalfa** [jlord/git-it#223]
I've followed this guide:

http://jlord.us/git-it/challenges/branches_arent_just_for_birds.html

I've created a new file as add-joannesalfa.txt

Then
I tried to do in this console:

```
joannesalfa:~/workspace/patchwork (gh-pages) $ git add -A
joannesalfa:~/workspace/patchwork (gh-pages) $ git commit -m "added contribuitor"
[gh-pages 24bc4c8] added contribuitor
 1 file changed, 1 insertion(+)
 create mode 100644 contributors/add-joannesalfa.txt
joannesalfa:~/workspace/patchwork (gh-pages) $ git push origin gh-pages
Username for 'https://github.com': joannesalfa
Password for 'https://joannesalfa@github.com': 
remote: Permission to jlord/patchwork.git denied to joannesalfa.
fatal: unable to access 'https://github.com/jlord/patchwork/': The requested URL returned error: 403
```

I don't know why it happened

**Comment by jlord** [comment]
Looks like you're pushing your branch to _my_ repository; the original `jlord/patchwork` that you forked, rather than _your_ fork `joannesalfa/patchwork`.

You can check what remotes you have set up by running `git remote -v`.

You should have one called `origin` that points to your fork and one called `upstream` that points to the original (mine). 

The names don't matter so much as long as you push to the right place. Hope that helps!
